#!/usr/bin/env python3
# add_hreflang.py - injects hreflang alternates into HTML files in the workspace
import os
from pathlib import Path
root = Path(__file__).parent
base = 'https://streamplanettv.online'
# Use language-region codes (ISO 639-1 + ISO 3166-1 alpha-2)
# Default mapping: Dutch (Netherlands), French (France), English (US).
langs = [('nl-NL',''), ('fr-FR','fr/'), ('en-US','en/')]
files = list(root.rglob('*.html'))
updated = []
for f in files:
    text = f.read_text(encoding='utf-8')
    # skip files that already have a full hreflang block marker
    if '<!-- HREFLANG-INJECTED -->' in text:
        continue
    # find <head> tag
    idx = text.lower().find('<head')
    if idx == -1:
        continue
    # find end of opening head tag '>'
    head_start = text.find('>', idx)
    if head_start == -1:
        continue
    # compute relative path
    rel = f.relative_to(root).as_posix()
    if rel == 'index.html':
        path = ''
    else:
        path = rel
    # build hreflang block
    lines = ['<!-- HREFLANG-INJECTED -->', '<!-- autogenerated hreflang - update generator if structure changes -->']
    for code, prefix in langs:
        if path == '':
            href = f"{base}/{prefix}" if prefix else f"{base}/"
        else:
            href = f"{base}/{prefix}{path}"
        # ensure single slash
        href = href.replace('//','/')
        href = href.replace('https:/','https://')
        lines.append(f'<link rel="alternate" hreflang="{code}" href="{href}">')
    # Set x-default to the Dutch root (nl-NL)
    lines.append(f'<link rel="alternate" hreflang="x-default" href="{base}/">')
    block = '\n  '.join(lines) + '\n'
    # insert after head_start
    new_text = text[:head_start+1] + '\n  ' + block + text[head_start+1:]
    f.write_text(new_text, encoding='utf-8')
    updated.append(str(f))
print('Updated files:', len(updated))
for u in updated:
    print(u)
